### ISSUE TITLE
Feature request: allow us to read files at specific offset

### ISSUE THREAD

**Issue by gaurav-gogia** [forensicanalysis/fslib#101]
Hey,

I noticed that you're using `io.ReaderAt` type to accept file handle. But I couldn't figure out how one could seek to a specific position in file and then send it,

Can we use a separate offset argument? 

I'll be happy to take this issue and send a PR with minimal changes

**Comment by cugu** [comment]
I don't fully understand what you want to do there. Some of the filesystems can not support `io.ReaderAt`, e.g. filesystems from archived formats like zip.

**Comment by gaurav-gogia** [comment]
I just want to seek to an offset and start reading from there so file system can be parsed. Like when we have multiple partitions in an MBR/GPT style image. Then we may have to seek to a certain partition offset where it starts from.

**Comment by cugu** [comment]
Have you considered to use [io.SectionReader](https://godocs.io/io#SectionReader) for that?

**Comment by gaurav-gogia** [comment]
Not yet, but will look into it now
