### ISSUE TITLE
The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by steve-offutt** [forensicanalysis/fslib#94]
Hey Jonas,

I am using fslib v0.15.1 in a custom collection tool. It is modeled after the zipcollector  (https://github.com/forensicanalysis/custom-collector/blob/master/zip-collector/main.go). I create a new `github.com/forensicanalysis/artifactcollector.collection.LiveCollector` object and use the `Collect` method on it to retrieve the `WindowsSystemRegistryFiles` defined here: https://github.com/forensicanalysis/artifacts/blob/fb6147d3c563b6ffeb50dacd7240d0b2dbbd1746/windows.yaml#L2808

The error I am seeing in my log file is: 
```
error opening file: not an NTFS parition (C []): open C:/Windows/System32/config/SAM: The process cannot access the file because it is being used by another process.
```
All files associated with this YAML object fail to be collected. 

The OS and build information:
Name: `Microsoft Windows Server 2012 R2 Datacenter`
Version: `6.3.9600 N/A Build 9600`
Memory: `16GB`

I also see some errors related to some of the user registry hives as well.

**Comment by steve-offutt** [comment]
The reason why I am opening an issue on this repo is because when I search the `forensicanalysis` github org for `not an NTFS parition` the only hit I get is here: https://github.com/forensicanalysis/fslib/blob/26ceae12a74a9d10564131803508baadbebcda55/systemfs/systemfs.go#L107

**Comment by cugu** [comment]
It might me that the server is using [ReFS](https://www.computerhope.com/issues/ch000713.htm#win7)? 

The access of files first tries "normal" file access using the operating system. This can fail for e.g. registry hives. In this case the file is accessed parsing the file system itself. But this only implemented for NTFS.

**Comment by steve-offutt** [comment]
@cugu Yeah, I thought the same thing that it may not be an NTFS file system. I went and verified that the drive is an NTFS volume, not an ReFS or otherwise.

**Comment by cugu** [comment]
It opens `\\.\C:` (you are admin, right?) and then parses the NTFS. Both of which can fail and error.
